POST http://localhost:39999/agentSpawner/spawn
Content-Type: application/json

{
    "id": "AIAgent@simple2",
    "messages": [
        {
            "type": "human",
            "content": "hello, tell me about yourself."
        }
    ]
}