POST http://localhost:39999/agentSpawner/spawn
Content-Type: application/json

{
    "id": "AIAgent@simpleOrchestrator",
    "messages": [
        {
            "type": "human",
            "content": "hello, I want you to create a team consists of 4 AI agents: 2 programmers + 1 manager (you) + 1 technical leader."
        }
    ]
}