POST http://localhost:39999/agent/spawn
Content-Type: application/json

{
    "messages": [
        {
            "type": "human",
            "content": "hello, send messages to a random agents."
        }
    ]
}