POST http://localhost:33999/agentSpawnerManager/spawn
Content-Type: application/json

{
    "id": "AIAgent@simple",
    "messages": [
        {
            "type": "human",
            "content": "hello, list all your tools."
        }
    ]
}